spawnerValues:
  'IRON_GOLEM': 156000
  'BLAZE': 75252
  'WITCH': 45615
  'SKELETON': 52750
  'ENDERMAN': 15750
  'ZOMBIE': 17250
  'SPIDER': 15850
  'CREEPER': 16350
  'COW': 7850
  'SHEEP': 7936
  'CHICKEN': 4256
  'PIG': 4800
  'RABBIT': 1235
easter:
  drops:
    '1':
      material: DIRT
      base64: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmU5NmM4NjhkNGEyNDM5YThmNDNhNDgyZDY0NjA4Y2E5N2ZiNTNmZGRhMjEyZmZjNGZhMDg5YzBlMzQwZTI4MCJ9fX0=
      amount: 1-1
      chance: 1
      canBeCooked: false
      data: 3
      name: '&dEaster Egg'
      lore:
        - '&7Sell in /easter!'
  shop:
    filleritems:
      '1':
        material: STAINED_GLASS_PANE
        amount: 1
        data: 0
        name: '&7'
        slots:
          - 0
          - 1
          - 2
          - 3
          - 5
          - 6
          - 7
          - 8
    shopitems:
      '1':
        itemid: '1'
        sellPrice: 5000
        slots:
          - 4
shop:
  filleritems:
    '1':
      material: STAINED_GLASS_PANE
      amount: 1
      data: 0
      name: '&7'
      slots:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 17
        - 18
        - 26
        - 27
        - 28
        - 29
        - 30
        - 31
        - 32
        - 33
        - 34
        - 35
  spawners:
    'RABBIT':
      price: 75200
      slots:
        - 10
    'PIG':
      price: 255000
      slots:
        - 11
    'CHICKEN':
      price: 258500
      slots:
        - 12
    'SHEEP':
      price: 475000
      slots:
        - 13
    'COW':
      price: 463200
      slots:
        - 14
    'PIG_ZOMBIE':
      price: 665000
      slots:
        - 15
    'CREEPER':
      price: 856000
      slots:
        - 16
    'SPIDER':
      price: 870000
      slots:
        - 19
    'ZOMBIE':
      price: 872500
      slots:
        - 20
    'ENDERMAN':
      price: 1025600
      slots:
        - 21
    'SKELETON':
      price: 2600000
      slots:
        - 22
    'WITCH':
      price: 2550000
      slots:
        - 23
    'BLAZE':
      price: 3750000
      slots:
        - 24
    'IRON_GOLEM':
      price: 7560000
      slots:
        - 25
mobDrops:
  RABBIT:
    1:
      material: RABBIT
      amount: 1-2
      chance: 100
      canBeCooked: true
      data: 0
    2:
      material: RABBIT_HIDE
      amount: 1-1
      chance: 10
      canBeCooked: false
      data: 0
  CHICKEN:
    1:
      material: RAW_CHICKEN
      amount: 1-2
      chance: 100
      canBeCooked: true
      data: 0
    2:
      material: FEATHER
      amount: 1-1
      chance: 50
      canBeCooked: false
      data: 0
    3:
      material: EGG
      amount: 1-1
      chance: 100
      canBeCooked: false
      data: 0
  PIG:
    1:
      material: PORK
      amount: 1-2
      chance: 100
      canBeCooked: true
      data: 0
  SHEEP:
    1:
      material: MUTTON
      amount: 1-2
      chance: 100
      canBeCooked: true
      data: 0
    2:
      material: WOOL
      amount: 1-1
      chance: 50
      canBeCooked: false
      data: 0
  COW:
    1:
      material: RAW_BEEF
      amount: 1-2
      chance: 100
      canBeCooked: true
      data: 0
    2:
      material: LEATHER
      amount: 1-1
      chance: 50
      canBeCooked: false
      data: 0
  CREEPER:
    1:
      material: SULPHUR
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
  ZOMBIE:
    1:
      material: ROTTEN_FLESH
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
  WITCH:
    1:
      material: REDSTONE
      amount: 0-2
      chance: 100
      canBeCooked: false
      data: 0
  SPIDER:
    1:
      material: STRING
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
    2:
      material: SPIDER_EYE
      amount: 0-1
      chance: 50
      canBeCooked: false
      data: 0
  SKELETON:
    1:
      material: BONE
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
    2:
      material: ARROW
      amount: 0-1
      chance: 100
      canBeCooked: false
      data: 0
  IRON_GOLEM:
    1:
      material: IRON_INGOT
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
    2:
      material: RED_ROSE
      amount: 0-1
      chance: 100
      canBeCooked: false
      data: 0
  BLAZE:
    1:
      material: BLAZE_ROD
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
  PIG_ZOMBIE:
    1:
      material: ROTTEN_FLESH
      amount: 1-2
      chance: 100
      canBeCooked: false
      data: 0
    2:
      material: GOLD_INGOT
      amount: 0-1
      chance: 100
      canBeCooked: false
      data: 0
  ENDERMAN:
    1:
      material: ENDER_PEARL
      amount: 0-1
      chance: 100
      canBeCooked: false
      data: 0
  SILVERFISH:
    1:
      material: NETHER_STAR
      amount: 1-1
      chance: 100
      canBeCooked: false
      data: 0
xP:
  RABBIT: 1-3
  CHICKEN: 1-3
  PIG: 1-3
  SHEEP: 1-3
  COW: 1-3
  CREEPER: 5-5
  ZOMBIE: 5-5
  WITCH: 0-2
  SPIDER: 5-5
  SKELETON: 5-5
  IRON_GOLEM: 0-0
  BLAZE: 10-10
  PIG_ZOMBIE: 5-5
  ENDERMAN: 5-5
  SILVERFISH: 1-3
spawnerGUI:
  buttons:
    '1':
      material: ARROW
      name: '&aPrevious Page'
      lore:
        - '&7Page: <page>'
      data: 0
      amount: 1
      buttonType: backarrow
    '2':
      material: ARROW
      name: '&aNext Page'
      lore:
        - '&7Page: <page>'
      data: 0
      amount: 1
      buttonType: nextarrow